---
title: "Homework #8 for STAT 547"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Dataset explored in this repo
This repo contains data on tumour microRNA expression in 133 samples of primary breast cancer tissue. Detailed [here](https://www.kaggle.com/rhostam/primary-breast-cancer-vs-normal-breast-tissue/home), as an interactive bioinformatics dataset, and [here](https://www.ncbi.nlm.nih.gov/pubmed/26056355), as the findings of a primary research article in the Clinical Chemistry journal. 

### Shiny app created in this repo
I used this data to develop a shiny app that reshapes and tidys this [data](https://github.com/STAT545-UBC-students/hw08-zhamadeh/blob/master/GSE58606_data.csv) in order to provide a friendly user interface to select one or more of the four microRNAs highlighted in the research paper and display a distribution of their expression levels accross all 133 samples. This interactive app overlays multiple microRNA distributions, provides a table of these values and includes an [image](https://github.com/STAT545-UBC-students/hw08-zhamadeh/blob/master/www/image.png) detailing the importance if microRNAs in the cell.


